# Generated by Django 3.2.3 on 2021-05-25 13:41

import autoslug.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210525_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=core.models.custom_slugify, unique_with=('created_at__month',)),
        ),
    ]
