# Generated by Django 3.2.3 on 2021-05-31 01:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_orders_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allow_access',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
