# Generated by Django 3.2.3 on 2021-07-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_addressf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addressf',
        ),
    ]
